services:
  web:
    container_name: interns_aid_web
    restart: always
    build: .
    command: gunicorn app:app -b 0.0.0.0:8000 --reload
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo-data:

