services:
  web:
    container_name: interns_aid_web
    restart: always
    build: .
    command: gunicorn app:app -w 2 --threads 2 -b 0.0.0.0:8000 --reload
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.prod

