"""empty message

Revision ID: 52114297bef9
Revises: a9dfbff051ac
Create Date: 2022-10-11 18:05:35.489635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52114297bef9"
down_revision = "a9dfbff051ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blocked_token_jti"), "blocked_token", ["jti"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blocked_token_jti"), table_name="blocked_token")
    op.drop_table("blocked_token")
    # ### end Alembic commands ###
