"""empty message

Revision ID: 63794aa17780
Revises: 52114297bef9
Create Date: 2022-10-12 18:49:36.110499

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '63794aa17780'
down_revision = '52114297bef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('duration', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('company',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('website', sa.String(), nullable=False),
                    sa.Column('location', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('coding',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('platform', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['assignment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('home',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['assignment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('internship',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('suggestion', sa.String(), nullable=True),
                    sa.Column('company_id', sa.String(), nullable=True),
                    sa.Column('assigment_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['assigment_id'], ['assignment.id'], ),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('attachment',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('internship_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('question',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('coding_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['coding_id'], ['coding.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tag',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('internship_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('question')
    op.drop_table('attachment')
    op.drop_table('internship')
    op.drop_table('home')
    op.drop_table('coding')
    op.drop_table('company')
    op.drop_table('assignment')
    # ### end Alembic commands ###
